@startuml
scale 2
enum TileType {
    +Sprite : Sprite
    +isPlaceable : boolean
    +id : into
    -RANDOM : Random
    -SIZE : int
    +getRandomDirt : Dirt
    +getRandomRoad : Road
    +Dirt0-11()
    +Road0-4()
}
+class Tile {
    -x, y, size : float
    -tile : TileType
    -Sprite: Sprite
    +Tile(float x, float y, float size, TileType tile)
    +draw() : void
    +getTile() : TileType 
    +setTile(TileType tile) : void
    +getX() , getY() : float
    +toString() : String
}
class TowerDefend {
	+SPEED = 1f : static final float 
	-spawnPoint : int
	-render : ShapeRenderer
    -camera : OrthographicCamera
	-room : TileGrid
	-enemy : Enemy
	+create()	
	+dispose()
	+render()
}
class Enemy {
    #SPEED = 1.0f, MULT = 0.3f  : static float
    #x, y: float
    #direction : int[]
    #startTile : Tile
    #grid:TileGrid
    #size, health, damage : int                     
    #sprites : Sprite[]
    #first = true : boolean
    Enemy(TileGrid grid, int size ,int health, int damage, Sprite[] textures)
    
    #remove()
    #setX(float deltaX)
    #setY(float deltaX)
    #update(float deltaX)
    #FindNextRoadTile(Tile now) : int[]
    #draw()
    #getStartTile() : Tile
    #getTileGrid() : TileGrid
}
class Basic
class Wave {
    -db : int
    -spawnTime : float
    -lastSpawnTime : float
    -enemyType : Enemy
    -enemies : ArrayList<Enemy>

    +Wave(int db, float spawnTime, Enemy enemyType)
    +update(float deltaTime)
    +spawn()
}

class Map {
    +map2D = null : int[][]
    +wasSetup = false : boolean
    +widthRange = -1, heightRange = -1 : int
    +startIndex = -1, endIndex = -1 : int
    +rand : Random 

    -void setup(int get_YRange, int get_XRange)
    -void GenerateIndexes()
    +int[][] generate(int get_YRange, int get_XRange)
    +int[][] getMap()
    +int getStart()
    #void writeOut()
}

class TileGrid{
    -start_X, start_Y : float
    -WINDOW_HEIGHT, WINDOW_WIDTH : float
    -map_grid2 : Tile[][]
    -map : int[][]
    +TileGrid(float start_X, float start_Y, float end_X, float end_Y)
    +generate() : void
    +draw() : void
    +getStartIndex() : void 
    +getTileDataesByCoord(float xCord, float yCord) : Tile
    +getTileDataesByInd(int oszlop, int sor) : Tile
    +setTileDataes(float xCord, float yCord,TileType type): Tile
}

class Artist{
    +WINDOW_WIDTH , WINDOW_HEIGHT: float
    +TILE_SIZE: int
    +batch : SpriteBatch
    +DrawTex(Sprite sp, float x, float y, float size) : void
    +DrawTex(Texture texture, float x, float y, float size)
    +getTexturesFromArea : Sprite[]
    +GetInternalTexture : Texture
    +GetTexture : Texture
    +Dispose : void
}

class Clock{
    +time : float
    +getTimer() : float
    +setDelta() : void
    +resetTimer() : void
}

TowerDefend "1" -- "N" Wave
TowerDefend -- Clock
TowerDefend -- TileGrid 
TileGrid o-- Map
TileGrid o-- Tile
Tile -- TileType
Wave "1" *-- "N" Enemy
Enemy <|-- Basic
Artist -- Enemy
Artist -- Tile
@enduml